% rebase('layout.tpl', title=title, year=year)

<div class = "page" style = "background-image: url('/static/images/wall1.jpg'); color: black">
<h2 style="font-size: 40px; background-color: rgba(255, 255, 255, 0.3); margin-left:10px; margin-right: 10px">{{ title }}</h2>
<h3 style="font-size: 25px; background-color: rgba(255, 255, 255, 0.3); margin-bottom: 10px; margin-left:10px; margin-right: 10px">{{ message }}</h3>
<center><img src="static/images/skategif.gif" alt="skating"></center>
<h style="font-size: 25px; background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-top: 20px; margin-left:10px; margin-right: 10px">
A Brief History of Skateboarding</h>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
Take an intimate look at some of the notable events that took place in the history of skateboarding. Hermetically sealed from the rest of the world, skateboardings history is naturally esoteric with several topics up for debate.</p>
<h style="font-size: 25px; background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-top: 10px; margin-left:10px; margin-right: 10px">
An Age Old Question: What is Skateboarding?</h>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
From the 1950s to present day 2020, skateboarding has grown into a multi-billion dollar industry impacting millions of lives across the world as an artform and a sport. In its history, skateboarding has inaugurated its own museums, awarded its own hall of fame and curated a self-documented history cementing a special place in the heart of freedom culture.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
The launch ramp of 1950’s California lit the torch of skateboarding to be handed off to each new generation over the coming eras. In these decades, skateboarding transcended through ups and downs of economic prosperity and mainstream popularity as different faces and figures shined in the spotlight or dominated the back alleys of urban performance.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
Between the youth of the world and those aging skateboarders who’ve watched it grow and change, the question of "What is skateboarding?" has undergone a metamorphosis with each passing of the baton. While we do our best to answer this question again here, we take our first push into a larger world. A world defined by the ultimate expression of freedom, movement, and an intimate look at the history of skateboarding.</p>
<h style="font-size: 25px; background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-top: 10px; margin-left:10px; margin-right: 10px">
All Downhill From Here</h>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
The origin of the skateboard is as ambiguous as the origin of our Universe. There are multiple reports from self-proclaimed skate-historians of who, what and where the first skateboards appeared. It is largely agreed upon that skateboards originated in the United States, first as crates of wood with roller derby skates attached to the underfoot. The earliest models had handlebars attached, like modern scooters but eventually the boxes were replaced by wooden planks and the handlebars scrapped for an experience more akin to surfing. These scooter-boxes were seen as far back as the late 1800s, but it wasn’t until the 1950s when wooden pallets with clay wheels were popularized on the downhill slopes of Southern California.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
Before commercial skateboards began appearing in 1959, the only way you could skate was by making your own board. These home-made skateboards would seed the DIY mentality ingrained in skateboarding today. In a raw and beautiful way, skateboarding began not from an industry but from the intense desire for one's own self expression. To understand this simple yet profound truth is our first glimpse into "what is skateboarding" and ultimately, what it means to be a skateboarder.</p>
<center><img src="static/images/skateboard.jpg" alt="skating" width= 500></center>
<h style="font-size: 25px; background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-top: 20px; margin-left:10px; margin-right: 10px">
Skateboarding’s First Slams</h>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
It’s difficult to imagine ourselves in the 1950s or 1970s DogTown eras–the birthplace of skateboarding. It would be even more difficult to imagine how much skateboarding would change since its conception. In the early 1960s, skateboard companies like Hobie and Makaha began advertising skating as “sidewalk surfing,” or an alternative to surfing when the waves were flat. By 1963, Makaha formed the first professional skateboarding team competing in the first ever skateboard competition later that year in Hermosa, California. While the remnants of early 1960s downhill skateboarding competitions take the form of death defying 2020 San Francisco hill-bombs, the freestyle competition formats and most tricks performed at the Hermosa competition are now but a distant memory to contemporary skateboarding.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
Even with its novelty in American sports, skateboarding popularity ultimately crashed by 1965. People were more likely to go to a roller derby competition than a skateboarding competition. Skateboarding in the media began advertising skating as a dangerous activity, while the clay wheels and handstands grew as tiresome as watching a hula-hooper for hours on end. To understand how skateboarding nearly perished is to understand ultimately why its earliest forms are no longer seen. But more importantly, comparing where skateboarding is today from these times, we see one of the greatest transformations of a sport and performance art in the 20th to 21st century.</p>
<h style="font-size: 25px; background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-top: 10px; margin-left:10px; margin-right: 10px">
Reinventing the (Skateboard) Wheel</h>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
Not figuratively–but literally. The skateboard wheel was reinvented by Frank Nasworthy, who introduced the urethane wheel to skateboarding in 1973. The new wheel, replacing the clunky clay wheels of the 1950 and 1960s, gripped the asphalt and pool walls like cleats to the grass. With the invention of the kick-tail alongside it, (a raised back end of the skateboard), a new definition of a professional skateboard was born. Skateboarding magazines sold at the local surf shop now had a horse to promote as a new craze of skateboarding began to expand world wide. Just three years after the new skateboard wheel, the first skatepark sprouted in Florida in 1976. Before the end of the decade, skateparks began to appear throughout North and South America, and soon after in the countries of Europe and Asia. Skateboarding’s 1970s rise to mainstream culture was best popularized by the 2005 film, “Lords of DogTown.” In 1975, as seen in the film, the Zephyr skateboarding team spearheaded by Tony Alva, showed the world skateboarding’s potential at the Ocean Festival in Del Mar, California. This moment in skateboarding history stands a cornerstone to its history and how skateboarding competitions would change in the coming decades.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
However, skateboarding would ultimately suffer another near-fatal crash at the approach of the 1980s. As dubious corporations from outside skateboarding began to infiltrate skateboarding competitions with trojan horse contracts and over-saturation of contests, skateboarding’s popularity fizzled out to a hermetic group of freedom seekers who prevailed in the empty backyard pools of America. Skateparks were no longer being constructed as sky-rocketing insurance costs latched onto the injury prone aspect of skating. And so, no longer accepted by SoCal parents or corporations seeking the next great fad, skating became the calling card of anti-establishment culture and the growing punk scene of the 1980s.</p>
<h style="font-size: 25px; background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-top: 10px; margin-left:10px; margin-right: 10px">
From 0 to 900</h>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
What Zephyr Skateboards did that year in Del Mar for the world of skateboarding wouldn’t be seen again until Tony Hawk landed his 900 in the 1999 X-Games. On June 27th, 1999, Tony Hawk dropped in at the Summer X-Games vert ramp for the 11th time to land the most recognizable trick in skateboarding history. At the time, no skateboarder could fathom just how much Tony Hawk’s two and a-half rotations would catapult skating into a new orbit of popularity. But by the time Tony Hawk had officially brought professional skateboarding to the mainstream spotlight again, skateboarding had already undergone an immense transformation throughout the 1980s and early 1990s. Most skateboarders and non-skaters alike will attest to the significance of Tony Hawk’s 900. But most non-skaters have no idea how important the 1980s and 1990s really were for skateboarding. In that time, street skateboarding was crafted by society’s outcasts. The blueprints for professional street skating were drawn and everything we have come to know about skateboarding media claimed their niches in the skate world.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
With the help of a new skateboard designed for aerial maneuvers, Rodney Mullen had invented several flip tricks by the 1980s, after Curt Lindgren invented the kickflip in 1978. The first street-only skateboarders Natas Kaupas and Mark ‘the Gonz’ Gonzales raised the bar once again by boardsliding the first handrails. Skateboarding evolved from the backyards of ramp builders into the parking lots of grocery stores riddled with red curbs. With the mainstream media turning a blind eye to skateboarding, skateboarders were given the chance to document their own culture through their own lens. This allowed skateboarders to wield the powers of producing their own media culture, combating the exact reasons why skateboarding had endured two major crashes in popularity in the late 1960s and early 1980s. With skateboarders fully in control of the factors of production of skate culture, the golden-era of street skateboarding blossomed in the years 1993-2006. We saw in these years the rise of Shorty’s and Chad Muska, videos like "Mouse" and "Yeah Right!" by Girl Skateboards, prominent international skate-teams like FLIP Skateboards, the celebrated LOVE Park era and the THPS video games franchise, as skateparks became synonymous with public park planning.</p>
<center><img src="static/images/skateboarding.jpg" alt="skating" width= 500></center>
<h style="font-size: 25px; background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-top: 20px; margin-left:10px; margin-right: 10px">
The Trick Heard Around the World</h>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
As skateboarding evolved in a post-Tony Hawk era, skateboarding’s interaction with society changed. Skateboarding deepened its roots in street skateboarding, as the definition of being a professional skateboarder shifted from competition skating to video parts while mainstream skate culture saw itself in novel forms of entertainment. The Tony Hawk Pro Skater video games franchise ensured Tony Hawk and "the ollie" were a household name. Bam Margera would go on to parody a pro-skateboarder career with a reality television show, “Viva-La-Bam.” As companies entered the fold, skateboarding gained more recognition and skating’s elite began making palpable salaries.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
Today, Street League and the X-Games draw the largest crowds in years. With more eyes comes more scrutiny, as today a juvenile distaste and adolescence is still associated with skateboarding in dominant forms of media. That being said, the off-shoots of skateboarding have also grown tremendously to tip the scales back into the hands of skateboarders. In the past five to ten years, female skateboarders are the sport’s largest growing demographic, with skateboarding now the largest female sport in Afghanistan. Skateparks are now found on every major continent of the World with countless clips filmed and posted to social media everyday. Skateboarding endures as one of the world’s most inclusive and accessible expressions of freedom.</p>
<p style="background-color: rgba(255, 255, 255, 0.7); margin-bottom: 10px; margin-left:10px; margin-right: 10px">
Skateboarding remains in a constant state of evolution. With each skateboarder not only defining their own relationship with their skateboard but what skateboarding means to them. With each contribution to skating it continues to be molded by those who need it most. Sometimes this means combating outside forces, sometimes this means inviting them in. Either way, the history of skateboarding is still being written and ultimately, thanks to the skateboarders who came before us, skating will forever be defined by those who truly love skateboarding, and no one else.</p>
